version: '3.8'
services:
  adminjs:
    build: .
    container_name: adminjs-container
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - my-network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adminjs
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="" --max_connections=1100 --general-log=1 --general-log-file=/tmp/mysql-general-log.log
    healthcheck:
      test: ["CMD", "sh", "-c", "cat /tmp/mysql-general-log.log | grep 'root@localhost on  using Socket'"]
      interval: 10s
      retries: 120
    volumes:
      - db_data:/var/lib/mysql
      - ./adminjs_backup.sql:/docker-entrypoint-initdb.d/adminjs_backup.sql
      - ./mysql-general-log.log:/tmp/mysql-general-log.log
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
